// Auto-generated by convert_assets.py — Jamagotchi sprite set
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_image_dsc_t jama_body_busker;
extern const lv_image_dsc_t jama_body_headliner;
extern const lv_image_dsc_t jama_body_loungeact;
extern const lv_image_dsc_t jama_body_openmic;
extern const lv_image_dsc_t jama_body_rookie;
extern const lv_image_dsc_t jama_face_busker_asleep_1;
extern const lv_image_dsc_t jama_face_busker_asleep_2;
extern const lv_image_dsc_t jama_face_busker_happy_1;
extern const lv_image_dsc_t jama_face_busker_happy_2;
extern const lv_image_dsc_t jama_face_busker_hungry_1;
extern const lv_image_dsc_t jama_face_busker_neutral_1;
extern const lv_image_dsc_t jama_face_busker_neutral_2;
extern const lv_image_dsc_t jama_face_busker_sick_1;
extern const lv_image_dsc_t jama_face_headliner_asleep_1;
extern const lv_image_dsc_t jama_face_headliner_asleep_2;
extern const lv_image_dsc_t jama_face_headliner_cool_1;
extern const lv_image_dsc_t jama_face_headliner_happy_1;
extern const lv_image_dsc_t jama_face_headliner_happy_2;
extern const lv_image_dsc_t jama_face_headliner_hungry_1;
extern const lv_image_dsc_t jama_face_headliner_neutral_1;
extern const lv_image_dsc_t jama_face_headliner_neutral_2;
extern const lv_image_dsc_t jama_face_headliner_sick_1;
extern const lv_image_dsc_t jama_face_loungeact_asleep_1;
extern const lv_image_dsc_t jama_face_loungeact_asleep_2;
extern const lv_image_dsc_t jama_face_loungeact_happy_1;
extern const lv_image_dsc_t jama_face_loungeact_happy_2;
extern const lv_image_dsc_t jama_face_loungeact_hungry_1;
extern const lv_image_dsc_t jama_face_loungeact_neutral_1;
extern const lv_image_dsc_t jama_face_loungeact_neutral_2;
extern const lv_image_dsc_t jama_face_loungeact_sick_1;
extern const lv_image_dsc_t jama_face_openmic_asleep_1;
extern const lv_image_dsc_t jama_face_openmic_asleep_2;
extern const lv_image_dsc_t jama_face_openmic_happy_1;
extern const lv_image_dsc_t jama_face_openmic_happy_2;
extern const lv_image_dsc_t jama_face_openmic_hungry_1;
extern const lv_image_dsc_t jama_face_openmic_neutral_1;
extern const lv_image_dsc_t jama_face_openmic_neutral_2;
extern const lv_image_dsc_t jama_face_openmic_sick_1;
extern const lv_image_dsc_t jama_face_rookie_asleep_1;
extern const lv_image_dsc_t jama_face_rookie_asleep_2;
extern const lv_image_dsc_t jama_face_rookie_happy_1;
extern const lv_image_dsc_t jama_face_rookie_happy_2;
extern const lv_image_dsc_t jama_face_rookie_hungry_1;
extern const lv_image_dsc_t jama_face_rookie_neutral_1;
extern const lv_image_dsc_t jama_face_rookie_neutral_2;
extern const lv_image_dsc_t jama_face_rookie_sick_1;
extern const lv_image_dsc_t jama_hair_busker;
extern const lv_image_dsc_t jama_hair_headliner;
extern const lv_image_dsc_t jama_hair_loungeact;
extern const lv_image_dsc_t jama_hair_openmic;
extern const lv_image_dsc_t jama_hair_rookie;
extern const lv_image_dsc_t jama_icon_attention_1;
extern const lv_image_dsc_t jama_icon_attention_2;
extern const lv_image_dsc_t jama_icon_medicine;
extern const lv_image_dsc_t jama_icon_mess;
extern const lv_image_dsc_t jama_icon_mess_color;
extern const lv_image_dsc_t jama_sprite_grave;

#ifdef __cplusplus
}
#endif
